[target.thumbv8m.main-none-eabihf]
runner = "probe-rs run --chip RP2350"
rustflags = ["-C", "link-arg=-Tlink.x", "-C", "link-arg=-Tdefmt.x"]

[build]
target = "thumbv8m.main-none-eabihf"

[net]
git-fetch-with-cli = true

[env]
DEFMT_LOG = "debug"
